spring.application.name=spring-tasklist-cli
# storage.type = mem  (default via @ConditionalOnProperty on InMemory repo)
# To use file-based storage, set:
# storage.type = file
# todo.file=tasks.csv

logging.level.root=INFO
spring.devtools.restart.enabled=false